version: '3.8'

services:
  live-query:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # if you have any env vars, list them here
      SPRING_PROFILES_ACTIVE: "prod"
    # optional: restart policy
    restart: unless-stopped
