name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Test & Coverage
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣  Get the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣  Set up JDK 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣  Cache Gradle artifacts
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4️⃣  Run tests + coverage check
      - name: Run tests & enforce coverage
        run: ./gradlew clean check --no-daemon

      # 5️⃣  Publish coverage report
      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
